# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'uc-health-hack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for uc-health-hack
  pod 'Alamofire'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'uc-health-hackTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'uc-health-hackUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
